name: Pullfrog
run-name: ${{ inputs.name || github.workflow }}

on:
  workflow_dispatch:
    inputs:
      prompt:
        type: string
        description: Agent prompt
      name:
        type: string
        description: Run name

permissions:
  contents: read

jobs:
  pullfrog:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: Run agent
        uses: pullfrog/pullfrog@ed800018463e1b84e8e3377f662173aed1da98b0
        with:
          prompt: ${{ inputs.prompt }}
